services:
  nginx:
    image: nginx:alpine
    container_name: lab7-nginx
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lab7-network

  php:
    build: .
    container_name: lab7-php
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - zookeeper
      - kafka
    networks:
      - lab7-network

  zookeeper:
    image: zookeeper:3.8
    container_name: lab7-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
    networks:
      - lab7-network

  kafka:
    image: apache/kafka:3.7.0
    container_name: lab7-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - zookeeper
    networks:
      - lab7-network

  adminer:
    image: adminer
    container_name: lab7-adminer
    ports:
      - '8081:8080'
    networks:
      - lab7-network

networks:
  lab7-network:
    driver: bridge
