services:
  nginx:
    image: nginx:alpine
    container_name: lab7-nginx
    ports:
      - '8080:80'
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lab7-network

  php:
    build: .
    container_name: lab7-php
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - zookeeper
      - kafka
    networks:
      - lab7-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: lab7-zookeeper
    ports:
      - '2181:2181'
    networks:
      - lab7-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: lab7-kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "lab7_topic:1:1"
    depends_on:
      - zookeeper
    networks:
      - lab7-network

  adminer:
    image: adminer
    container_name: lab7-adminer
    ports:
      - '8081:8080'
    networks:
      - lab7-network

networks:
  lab7-network:
    driver: bridge
